datasources:
  default:
    connection:
      url: ${MONGO_URL}
    objectFiles:
      - "./steedos-app/**"
# 文件存储     
public:
  cfs:
    store: ${STEEDOS_CFS_STORE}
  templateSpaceId: 'template'
  webservices:
    jsreport:
      url: ${JSREPORT_URL}
      urlProvideForJsreport: ${JSREPORT_TO_ACQUIRE_DATA_URL}
    app_exchange:
      url: ${STEEDOS_APP_EXCHANGE_URL}
cfs:
  store: ${STEEDOS_CFS_STORE}
  aliyun:
    region: ${STEEDOS_CFS_ALIYUN_REGION}
    bucket: ${STEEDOS_CFS_ALIYUN_BUCKET}
    folder: ${STEEDOS_CFS_ALIYUN_FOLDER}
    accessKeyId: ${STEEDOS_CFS_ALIYUN_ACCESSKEYID}
    secretAccessKey: ${STEEDOS_CFS_ALIYUN_SECRETACCESSKEY}
  aws:
    endpoint: ${STEEDOS_CFS_AWS_S3_ENDPOINT}
    bucket: ${STEEDOS_CFS_AWS_S3_BUCKET}
    accessKeyId: ${STEEDOS_CFS_AWS_S3_ACCESS_KEY_ID}
    secretAccessKey: ${STEEDOS_CFS_AWS_S3_SECRET_ACCESS_KEY}
    s3ForcePathStyle: ${STEEDOS_CFS_AWS_S3_FORCE_PATH_STYLE}
    signatureVersion: ${STEEDOS_CFS_AWS_S3_SIGNATURE_VERSION}
  steedosCloud:
    bucket: ${STEEDOS_CFS_CLOUD_BUCKET}
    endpoint: ${STEEDOS_CFS_CLOUD_ENDPOINT}
    accessKeyId: ${STEEDOS_CFS_CLOUD_ACCESSKEYID}
    secretAccessKey: ${STEEDOS_CFS_CLOUD_SECRETACCESSKEY}
# 登陆界面配置
tenant:
  _id: ${STEEDOS_CLOUD_SPACE_ID}
  name: 华炎魔方
  logo_url: ${STEEDOS_CLOUD_LOGO_URL}
  logo_square_url: ${STEEDOS_CLOUD_LOGO_SQUARE_URL}
  background_url:
  enable_register: ${STEEDOS_TENANT_CONFIG_ENABLE_REGISTER} # 启用注册功能 true / false
  enable_forget_password: false  # 找回密码 true / false
  enable_create_tenant: false # 允许创建企业 true / false
  enable_password_login: true # 使用密码登录 true / false
  enable_bind_email: false # 强制绑定邮箱
  enable_bind_mobile: false # 强制绑定手机号
# 发送短信配置 （用于通过手机短信登录和接受账户提醒消息）
sms:
  qcloud:
    smsqueue_interval: 1000
    sdkappid: ${STEEDOS_SMS_QCLOUD_SDKAPPID}
    appkey: ${STEEDOS_SMS_QCLOUD_APPKEY}
    signname: ${STEEDOS_SMS_QCLOUD_SIGNNAME}
# 邮件配置 （配置SMTP服务的相关参数，用于系统发送推送邮件）
email:
  from: ${MAIL_FROM}
  url: ${MAIL_URL}
  signname: ${MAIL_SIGNNAME}
# 定时任务配置
cron:
  instancerecordqueue_interval: 10000 # 对象流程队列的轮询间隔(单位毫秒)
  mailqueue_interval: 10000 # 邮件队列的轮询间隔(单位毫秒)
  # push_interval: 1000 # 消息推送的轮询间隔(单位毫秒)
  webhookqueue_interval: 1000 #流程触发器队列的轮询间隔(单位毫秒)
dingtalk:
  api_Key: ${APIKEY}
  log_path: ${DING_LOGPATH}
qywx:
  api_Key: ${APIKEY}
  log_path: ${QYWX_LOGPATH}
push:
  apn:
    keyData: ${STEEDOS_PUSH_APN_DATA}
    certData: ${STEEDOS_PUSH_APN_DATA}
  gcm:
    apiKey: xxx
  xinge:
    accessId: ${STEEDOS_PUSH_XINGE_ACCESSID}
    secretKey: ${STEEDOS_PUSH_XINGE_SECRETKEY}
  huawei:
    appId: ${STEEDOS_PUSH_HUAWEI_APPID}
    appSecret: ${STEEDOS_PUSH_HUAWEI_APPSECRET}
    appPkgName: ${STEEDOS_PUSH_HUAWEI_APPPKGNAME}
  mi:
    appSecret: ${STEEDOS_PUSH_MI_APPSECRET}
    production: ${STEEDOS_PUSH_MI_PRODUCTION}
pay:
  weixin:
    appid: ${PAY_WEIXIN_APPID}
    mch_id: ${PAY_WEIXIN_MCH_ID}
    partner_key: ${PAY_WEIXIN_PARTNER_KEY}
